name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get Date
      id: get-date
      run: echo "date=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

    - name: Buildozer Action
      uses: ArtemGovorov/buildozer-action@v1
      with:
        workdir: .
        buildozer_version: master

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Sultan-Logic-App-${{ steps.get-date.outputs.date }}
        path: bin/*.apk
